import { Controller, Post, Req, Res, Headers, UseGuards, Request } from '@nestjs/common';
import { PaymentService } from './payment.service';
import { JwtAuthGuard } from '../auth/jwt-auth.guard';

@Controller('payment')
export class PaymentController {
  constructor(private readonly paymentService: PaymentService) {}

  @UseGuards(JwtAuthGuard)
  @Post('checkout')
  async createCheckoutSession(@Request() req: any) {
    const userId = req.user.id;
    return this.paymentService.createCheckoutSession(userId);
  }

  @Post('webhook')
  async handleWebhook(
    @Headers('stripe-signature') signature: string,
    @Req() req: any,
  ) {
    // req.rawBody is generated by enabling rawBody in main.ts
    const payload = req.rawBody;
    return this.paymentService.handleWebhook(signature, payload);
  }
}
